### ISSUE TITLE
About the code

### ISSUE THREAD

**Issue by lucasliunju** [shariqiqbal2810/MAAC#1]
Hi,
I'm very sorry to trouble you. I am reading your paper MAAC and I find that the result is  compare with COMA. So I want to ask whether you can open the code about COMA.

Thanks!

**Comment by shariqiqbal2810** [comment]
Hi,

I haven't had a chance to clean up and publish the code for COMA, but it appears that the authors have made an implementation available here: https://github.com/oxwhirl/pymarl_alpha

Hope this helps!
