### ISSUE TITLE
How to evaluate and test the training result? 

### ISSUE THREAD

**Issue by wanghuimu** [shariqiqbal2810/MAAC#12]
Hi, 
    Your codes are written very well~ Thanks for your great job! But in all folders, I only found codes for training the model and I didn’t find the codes for testing or evaluating the trained model in  environments , would you mind uploading the evaluation codes file for testing or evaluating?
     Thank you~

**Comment by wang88256187** [comment]
> Hi,
> Your codes are written very well~ Thanks for your great job! But in all folders, I only found codes for training the model and I didn’t find the codes for testing or evaluating the trained model in environments , would you mind uploading the evaluation codes file for testing or evaluating?
> Thank you~

hi, Have you got the final result ? why did I always meet the issue that the machine memorry always overflow? Can you give me some reason?

**Comment by niniuba123456** [comment]
> Hi,
> Your codes are written very well~ Thanks for your great job! But in all folders, I only found codes for training the model and I didn’t find the codes for testing or evaluating the trained model in environments , would you mind uploading the evaluation codes file for testing or evaluating?
> Thank you~

Did you solve this problem?

**Comment by shariqiqbal2810** [comment]
Hi,

I do not have the bandwidth to release evaluation code at the moment. The process for evaluating a trained model is as such:

- Load the saved model file using [`AttentionSAC.init_from_save(<filename>)`](https://github.com/shariqiqbal2810/MAAC/blob/bd263afce709795293964badd16655b5747b9056/algorithms/attention_sac.py#L265)
- Rollout in the environment using the appropriate number of maximum steps (detailed in README)
- Keep track of total rewards per episode per agent
- Average episodic rewards (across Rovers for Rover-Tower and across Collectors for CTC) and report these values.
