### ISSUE TITLE
connection.py

### ISSUE THREAD

**Issue by agharibr2019** [shariqiqbal2810/MAAC#17]
Dear Shariq,

I am trying to run this code and I already have installed all of the requirements, but this is the error I have face:
python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
I was wondering if you could let me know how can I solve it.

Bests, 
Azadeh

**Comment by zhoushiyang12** [comment]
I have the same issue，

**Comment by shariqiqbal2810** [comment]
I will need the full stack trace to know what's going on. But first I would double-check to make sure all of the package versions match the readme (especially for gym and baselines).

**Comment by zhoushiyang12** [comment]
Thank you for your notice.I have solved this problem by update the baselines to match the readme.It's   really a good project.
