### ISSUE TITLE
How to visualize the result?

### ISSUE THREAD

**Issue by sanshibayuan** [shariqiqbal2810/MAAC#4]
Hi, I am wondering whether you have a result of the visualization so that the effectiveness of the algorithm on the two new envs can be seen directly?
I noticed that in baselines,common.vec_env, the VecEnv class has not defined the Render function, is there any idea I can do the visualization? 
Thank you so much!

**Comment by shariqiqbal2810** [comment]
Hi! You should be able to use the unwrapped base environment to render and evaluate. VecEnv is just used for parallelization for faster training.
