### ISSUE TITLE
About environment

### ISSUE THREAD

**Issue by YaozuGen** [shariqiqbal2810/MAAC#6]
This unwrapped multiagent environment has abstract reset() method.
worker() method in make_env.py may be modified as follows:
![Uploading as.GIF…]()
errors occur without these modifications in my python3.5. what about yours?

**Comment by shariqiqbal2810** [comment]
I can't see the image that you included, but I think the issue is with the version of OpenAI Gym. The older version of Gym that I specify in the README (0.9.4) works with this code. I believe they have since changed the way that abstract methods are set up.
