### ISSUE TITLE
2 agents modification

### ISSUE THREAD

**Issue by emanuelepesce** [shariqiqbal2810/MAAC#8]
I noticed that the code creashes when 2 agents are used. since there are problems with the dimension for the sum function in ```critics.py``` line 138.

I managed to sort it out in this way:
```
for i, a_i in enumerate(agents):
    if max(agents) == 1:
        head_entropies = [(-((probs + 1e-8).log() * probs).squeeze().sum(0)
        .mean()) for probs in all_attend_probs[i]]
    else:
        head_entropies = [(-((probs + 1e-8).log() * probs).squeeze().sum(1)
                        .mean()) for probs in all_attend_probs[i]]
```

Does it sound good by you?

**Comment by shariqiqbal2810** [comment]
Thanks for the heads up! Please feel free to make a pull request. We never tested with 2 agents since the attention mechanism isn't making any choices in that case (it operates over all the *other* agents of which there is only 1 when there are 2 agents).
