### ISSUE TITLE
How to run your code in other scenarios, i.e., cooperative navigation

### ISSUE THREAD

**Issue by soada** [shariqiqbal2810/MAAC#9]
Hi, thanks for your great job! I met a problem when I run your code in other scenarios, i.e., simple_spread. The command I used is " python main.py simple_spread dataxx --use_gpu". Is it caused by the version of gym. I have tested both gym 0.9.4 and 0.12.5, but the following problem still exists. Could you please give me some advice on the problem? Thanks very much!
![image](https://user-images.githubusercontent.com/20594764/59842566-5bb67e80-9389-11e9-8de5-8427f3819ff8.png)
![image](https://user-images.githubusercontent.com/20594764/59842575-5f4a0580-9389-11e9-9ce5-2387b38f045b.png)

**Comment by shariqiqbal2810** [comment]
Hi,

This looks like it was caused by the gym version not matching the one I specify in the README.

**Comment by soada** [comment]
Thanks for your comments! I have found that the gym version 0.9.4 is not matched with the baseline version. 
![image](https://user-images.githubusercontent.com/20594764/59959918-8d972480-94f2-11e9-8ec9-19d521615c0b.png)
When installing the baselines, the following problem occurs:
![image](https://user-images.githubusercontent.com/20594764/59959934-b0293d80-94f2-11e9-8acf-5f973f026fb5.png)
Could you please give me some advice? Thanks!

**Comment by shariqiqbal2810** [comment]
It looks like the version of baselines you are using (0.1.5) is wrong. Please check the README. There is a specific commit that I used, so you need to clone the repo, check out that commit, and install using `pip install -e .` from the base directory.

**Comment by soada** [comment]
Thank you very much! I have solved the problem!
